version: '3'

services:
  postgres:
    image: postgres:13.11
    container_name: ecom-postgres
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_DB=${DB_NAME}
  redis:
    image: redis:7.0.11
    container_name: ecom-redis
    ports:
      - "6379:6379"
  mailtrap:
    image: eaudeweb/mailtrap
    container_name: mailtrap
    ports:
      - "80:80"
    environment:
      - MT_USER=${MAILTRAP_USER}
      - MT_PASSWD=${MAILTRAP_PASSWD}